CREATE TABLE IF NOT EXISTS accounts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  balance BIGINT DEFAULT 0,
  number VARCHAR(15) NOT NULL UNIQUE,
  branch VARCHAR(10) NOT NULL DEFAULT '3018-X',
  is_active BOOLEAN DEFAULT true,
  holder_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (holder_id) REFERENCES holders(id)
);
